# Generated by Django 4.2 on 2023-04-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=30, null=True, verbose_name='Автор')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
