# Generated by Django 4.2 on 2023-04-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='group',
            field=models.CharField(blank=True, choices=[('Детектив', 'Detective'), ('Роман', 'Roman')], max_length=10, verbose_name='Литературная группа'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Флаг видимости'),
        ),
    ]
